//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosWar.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CosmosWar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _000 {
            get {
                object obj = ResourceManager.GetObject("_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _001 {
            get {
                object obj = ResourceManager.GetObject("_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _002 {
            get {
                object obj = ResourceManager.GetObject("_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _003 {
            get {
                object obj = ResourceManager.GetObject("_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _004 {
            get {
                object obj = ResourceManager.GetObject("_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _005 {
            get {
                object obj = ResourceManager.GetObject("_005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _006 {
            get {
                object obj = ResourceManager.GetObject("_006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _007 {
            get {
                object obj = ResourceManager.GetObject("_007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _098 {
            get {
                object obj = ResourceManager.GetObject("_098", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _099 {
            get {
                object obj = ResourceManager.GetObject("_099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1mgameslogo {
            get {
                object obj = ResourceManager.GetObject("_1mgameslogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [棒旋星系L11区域]
        ///6,4,5,4,1,1,6,4,4,4,2,1,2,0,0,1,0,0,0,2,2,1,1,0,0,0,0,0
        ///4,6,4,1,1,0,1,7,5,4,0,0,0,3,0,0,0,0,0,0,0,1,1,1,1,0,0,0
        ///4,4,1,2,0,2,0,1,3,3,0,0,2,0,0,0,5,4,0,0,1,1,2,2,2,0,0,0
        ///4,1,3,1,3,4,1,1,2,1,2,2,1,1,0,0,5,6,0,0,1,1,2,3,1,0,1,0
        ///1,1,0,0,4,5,2,3,4,4,4,3,1,1,1,0,3,4,0,0,0,1,0,3,1,0,0,0
        ///0,0,0,1,1,4,4,4,0,5,2,1,3,1,0,0,0,1,0,0,0,1,1,3,1,0,0,3
        ///0,1,0,1,1,0,1,1,0,0,0,0,1,2,0,0,0,1,1,0,0,0,0,1,0,0,2,0
        ///0,0,0,0,0,0,0,0,0,1,3,4,1,0,0,0,1,1,0,0,0,1,0,0,0,0,3,2
        ///0,0,1,0,1,0,0,0,1,1,1,4,1,0,0,0,0,0,1,0,0,1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area1 {
            get {
                return ResourceManager.GetString("Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BEGIN 
        ///SETCOMMENT(MapSize:W:27 H:19)
        ///SETGOLD R 1500
        ///SETGOLD B 1500
        ///SETSTART B 0,0
        ///SETSTART R 27,19
        ///SETFACTORY B 1,0
        ///SETFACTORY R 26,19
        ///SETUNIT B 2 3,0 3
        ///SETUNIT B 4 0,3 3
        ///SETUNIT B 27 0,0 16
        ///SETUNIT B 32 1,0 18
        ///SETUNIT B 18 1,1 14
        ///SETUNIT R 2 26,19 3
        ///SETUNIT R 5 25,15 3
        ///SETUNIT R 21 27,18 16
        ///SETUNIT R 31 26,18 18
        ///SETUNIT R 29 27,19 15
        ///DEFINEMANUFACTUREUNITTYPES R 2,5,6,7,14,16,19,20,21,31,33
        ///DEFINEMANUFACTUREUNITTYPES B 3,4,8,12,15,17,18,25,26,27,32
        ///SETROUNDGOLDGAIN R 150
        ///SETROUNDGOLDGA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area1_setting {
            get {
                return ResourceManager.GetString("Area1.setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [棒旋星系L11区域]
        ///6,4,5,4,1,1,6,4,4,4,2,1,2,0,0,1,0,0,0,2,2,1,1,0,0,0,0,0
        ///4,6,4,1,1,0,1,7,5,4,0,0,0,3,0,0,0,0,0,0,0,1,1,1,1,0,0,0
        ///4,4,1,2,0,2,0,1,3,3,0,0,2,0,0,0,5,4,0,0,1,1,2,2,2,0,0,0
        ///4,1,3,1,3,4,1,1,2,1,2,2,1,1,0,0,5,6,0,0,1,1,2,3,1,0,1,0
        ///1,1,0,0,4,5,2,3,4,4,4,3,1,1,1,0,3,4,0,0,0,1,0,3,1,0,0,0
        ///0,0,0,1,1,4,4,4,0,5,2,1,3,1,0,0,0,1,0,0,0,1,1,3,1,0,0,3
        ///0,1,0,1,1,0,1,1,0,0,0,0,1,2,0,0,0,1,1,0,0,0,0,1,0,0,2,0
        ///0,0,0,0,0,0,0,0,0,1,3,4,1,0,0,0,1,1,0,0,0,1,0,0,0,0,3,2
        ///0,0,1,0,1,0,0,0,1,1,1,4,1,0,0,0,0,0,1,0,0,1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area2 {
            get {
                return ResourceManager.GetString("Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BEGIN 
        ///SETCOMMENT(MapSize:W:27 H:19)
        ///SETGOLD R 1500
        ///SETGOLD B 1500
        ///SETSTART B 0,0
        ///SETSTART R 27,19
        ///SETFACTORY B 1,0
        ///SETFACTORY R 26,19
        ///SETUNIT B 2 3,0 3
        ///SETUNIT B 4 0,3 3
        ///SETUNIT B 27 0,0 16
        ///SETUNIT B 32 1,0 18
        ///SETUNIT B 18 1,1 14
        ///SETUNIT R 2 26,19 3
        ///SETUNIT R 5 25,15 3
        ///SETUNIT R 21 27,18 16
        ///SETUNIT R 31 26,18 18
        ///SETUNIT R 29 27,19 15
        ///DEFINEMANUFACTUREUNITTYPES R 2,5,6,7,14,16,19,20,21,31,33
        ///DEFINEMANUFACTUREUNITTYPES B 3,4,8,12,15,17,18,25,26,27,32
        ///SETROUNDGOLDGAIN R 150
        ///SETROUNDGOLDGA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area2_setting {
            get {
                return ResourceManager.GetString("Area2_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [棒旋星系L11区域]
        ///6,4,5,4,1,1,6,4,4,4,2,1,2,0,0,1,0,0,0,2,2,1,1,0,0,0,0,0
        ///4,6,4,1,1,0,1,7,5,4,0,0,0,3,0,0,0,0,0,0,0,1,1,1,1,0,0,0
        ///4,4,1,2,0,2,0,1,3,3,0,0,2,0,0,0,5,4,0,0,1,1,2,2,2,0,0,0
        ///4,1,3,1,3,4,1,1,2,1,2,2,1,1,0,0,5,6,0,0,1,1,2,3,1,0,1,0
        ///1,1,0,0,4,5,2,3,4,4,4,3,1,1,1,0,3,4,0,0,0,1,0,3,1,0,0,0
        ///0,0,0,1,1,4,4,4,0,5,2,1,3,1,0,0,0,1,0,0,0,1,1,3,1,0,0,3
        ///0,1,0,1,1,0,1,1,0,0,0,0,1,2,0,0,0,1,1,0,0,0,0,1,0,0,2,0
        ///0,0,0,0,0,0,0,0,0,1,3,4,1,0,0,0,1,1,0,0,0,1,0,0,0,0,3,2
        ///0,0,1,0,1,0,0,0,1,1,1,4,1,0,0,0,0,0,1,0,0,1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area3 {
            get {
                return ResourceManager.GetString("Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BEGIN 
        ///SETCOMMENT(MapSize:W:27 H:19)
        ///SETGOLD R 1500
        ///SETGOLD B 1500
        ///SETSTART B 0,0
        ///SETSTART R 27,19
        ///SETFACTORY B 1,0
        ///SETFACTORY R 26,19
        ///SETUNIT B 2 3,0 3
        ///SETUNIT B 4 0,3 3
        ///SETUNIT B 27 0,0 16
        ///SETUNIT B 32 1,0 18
        ///SETUNIT B 18 1,1 14
        ///SETUNIT R 2 26,19 3
        ///SETUNIT R 5 25,15 3
        ///SETUNIT R 21 27,18 16
        ///SETUNIT R 31 26,18 18
        ///SETUNIT R 29 27,19 15
        ///DEFINEMANUFACTUREUNITTYPES R 2,5,6,7,14,16,19,20,21,31,33
        ///DEFINEMANUFACTUREUNITTYPES B 3,4,8,12,15,17,18,25,26,27,32
        ///SETROUNDGOLDGAIN R 150
        ///SETROUNDGOLDGA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area3_setting {
            get {
                return ResourceManager.GetString("Area3_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [棒旋星系L11区域]
        ///6,4,5,4,1,1,6,4,4,4,2,1,2,0,0,1,0,0,0,2,2,1,1,0,0,0,0,0
        ///4,6,4,1,1,0,1,7,5,4,0,0,0,3,0,0,0,0,0,0,0,1,1,1,1,0,0,0
        ///4,4,1,2,0,2,0,1,3,3,0,0,2,0,0,0,5,4,0,0,1,1,2,2,2,0,0,0
        ///4,1,3,1,3,4,1,1,2,1,2,2,1,1,0,0,5,6,0,0,1,1,2,3,1,0,1,0
        ///1,1,0,0,4,5,2,3,4,4,4,3,1,1,1,0,3,4,0,0,0,1,0,3,1,0,0,0
        ///0,0,0,1,1,4,4,4,0,5,2,1,3,1,0,0,0,1,0,0,0,1,1,3,1,0,0,3
        ///0,1,0,1,1,0,1,1,0,0,0,0,1,2,0,0,0,1,1,0,0,0,0,1,0,0,2,0
        ///0,0,0,0,0,0,0,0,0,1,3,4,1,0,0,0,1,1,0,0,0,1,0,0,0,0,3,2
        ///0,0,1,0,1,0,0,0,1,1,1,4,1,0,0,0,0,0,1,0,0,1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area4 {
            get {
                return ResourceManager.GetString("Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BEGIN 
        ///SETCOMMENT(MapSize:W:27 H:19)
        ///SETGOLD R 1500
        ///SETGOLD B 1500
        ///SETSTART B 0,0
        ///SETSTART R 27,19
        ///SETFACTORY B 1,0
        ///SETFACTORY R 26,19
        ///SETUNIT B 2 3,0 3
        ///SETUNIT B 4 0,3 3
        ///SETUNIT B 27 0,0 16
        ///SETUNIT B 32 1,0 18
        ///SETUNIT B 18 1,1 14
        ///SETUNIT R 2 26,19 3
        ///SETUNIT R 5 25,15 3
        ///SETUNIT R 21 27,18 16
        ///SETUNIT R 31 26,18 18
        ///SETUNIT R 29 27,19 15
        ///DEFINEMANUFACTUREUNITTYPES R 2,5,6,7,14,16,19,20,21,31,33
        ///DEFINEMANUFACTUREUNITTYPES B 3,4,8,12,15,17,18,25,26,27,32
        ///SETROUNDGOLDGAIN R 150
        ///SETROUNDGOLDGA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Area4_setting {
            get {
                return ResourceManager.GetString("Area4_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BackGround {
            get {
                object obj = ResourceManager.GetObject("BackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Robot4screenloop {
            get {
                object obj = ResourceManager.GetObject("Robot4screenloop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB001 {
            get {
                object obj = ResourceManager.GetObject("UnitB001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB002 {
            get {
                object obj = ResourceManager.GetObject("UnitB002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB003 {
            get {
                object obj = ResourceManager.GetObject("UnitB003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB004 {
            get {
                object obj = ResourceManager.GetObject("UnitB004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB005 {
            get {
                object obj = ResourceManager.GetObject("UnitB005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB006 {
            get {
                object obj = ResourceManager.GetObject("UnitB006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB007 {
            get {
                object obj = ResourceManager.GetObject("UnitB007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB008 {
            get {
                object obj = ResourceManager.GetObject("UnitB008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB009 {
            get {
                object obj = ResourceManager.GetObject("UnitB009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB010 {
            get {
                object obj = ResourceManager.GetObject("UnitB010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB011 {
            get {
                object obj = ResourceManager.GetObject("UnitB011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB012 {
            get {
                object obj = ResourceManager.GetObject("UnitB012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB013 {
            get {
                object obj = ResourceManager.GetObject("UnitB013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB014 {
            get {
                object obj = ResourceManager.GetObject("UnitB014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB015 {
            get {
                object obj = ResourceManager.GetObject("UnitB015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB016 {
            get {
                object obj = ResourceManager.GetObject("UnitB016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB017 {
            get {
                object obj = ResourceManager.GetObject("UnitB017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB018 {
            get {
                object obj = ResourceManager.GetObject("UnitB018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB019 {
            get {
                object obj = ResourceManager.GetObject("UnitB019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB020 {
            get {
                object obj = ResourceManager.GetObject("UnitB020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB021 {
            get {
                object obj = ResourceManager.GetObject("UnitB021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB022 {
            get {
                object obj = ResourceManager.GetObject("UnitB022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB023 {
            get {
                object obj = ResourceManager.GetObject("UnitB023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB024 {
            get {
                object obj = ResourceManager.GetObject("UnitB024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB025 {
            get {
                object obj = ResourceManager.GetObject("UnitB025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB026 {
            get {
                object obj = ResourceManager.GetObject("UnitB026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB027 {
            get {
                object obj = ResourceManager.GetObject("UnitB027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB028 {
            get {
                object obj = ResourceManager.GetObject("UnitB028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB029 {
            get {
                object obj = ResourceManager.GetObject("UnitB029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB030 {
            get {
                object obj = ResourceManager.GetObject("UnitB030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB031 {
            get {
                object obj = ResourceManager.GetObject("UnitB031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB032 {
            get {
                object obj = ResourceManager.GetObject("UnitB032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitB033 {
            get {
                object obj = ResourceManager.GetObject("UnitB033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR001 {
            get {
                object obj = ResourceManager.GetObject("UnitR001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR002 {
            get {
                object obj = ResourceManager.GetObject("UnitR002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR003 {
            get {
                object obj = ResourceManager.GetObject("UnitR003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR004 {
            get {
                object obj = ResourceManager.GetObject("UnitR004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR005 {
            get {
                object obj = ResourceManager.GetObject("UnitR005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR006 {
            get {
                object obj = ResourceManager.GetObject("UnitR006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR007 {
            get {
                object obj = ResourceManager.GetObject("UnitR007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR008 {
            get {
                object obj = ResourceManager.GetObject("UnitR008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR009 {
            get {
                object obj = ResourceManager.GetObject("UnitR009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR010 {
            get {
                object obj = ResourceManager.GetObject("UnitR010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR011 {
            get {
                object obj = ResourceManager.GetObject("UnitR011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR012 {
            get {
                object obj = ResourceManager.GetObject("UnitR012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR013 {
            get {
                object obj = ResourceManager.GetObject("UnitR013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR014 {
            get {
                object obj = ResourceManager.GetObject("UnitR014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR015 {
            get {
                object obj = ResourceManager.GetObject("UnitR015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR016 {
            get {
                object obj = ResourceManager.GetObject("UnitR016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR017 {
            get {
                object obj = ResourceManager.GetObject("UnitR017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR018 {
            get {
                object obj = ResourceManager.GetObject("UnitR018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR019 {
            get {
                object obj = ResourceManager.GetObject("UnitR019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR020 {
            get {
                object obj = ResourceManager.GetObject("UnitR020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR021 {
            get {
                object obj = ResourceManager.GetObject("UnitR021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR022 {
            get {
                object obj = ResourceManager.GetObject("UnitR022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR023 {
            get {
                object obj = ResourceManager.GetObject("UnitR023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR024 {
            get {
                object obj = ResourceManager.GetObject("UnitR024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR025 {
            get {
                object obj = ResourceManager.GetObject("UnitR025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR026 {
            get {
                object obj = ResourceManager.GetObject("UnitR026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR027 {
            get {
                object obj = ResourceManager.GetObject("UnitR027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR028 {
            get {
                object obj = ResourceManager.GetObject("UnitR028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR029 {
            get {
                object obj = ResourceManager.GetObject("UnitR029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR030 {
            get {
                object obj = ResourceManager.GetObject("UnitR030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR031 {
            get {
                object obj = ResourceManager.GetObject("UnitR031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR032 {
            get {
                object obj = ResourceManager.GetObject("UnitR032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UnitR033 {
            get {
                object obj = ResourceManager.GetObject("UnitR033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
